services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: unless-stopped

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redis"
    volumes:
      - "./data/redis:/data"
    restart: unless-stopped

  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
    restart: unless-stopped

  client:
    build:
      context: apps/client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    links:
      - api
    restart: unless-stopped

  dashboard:
    build:
      context: apps/dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    links:
      - api
    restart: unless-stopped

  bot:
    build:
      context: apps/bot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    links:
      - api
    restart: unless-stopped
