# triggered github action that start build of all docker images
on: [ workflow_call, workflow_dispatch ]
name: Build Docker images job
jobs:
  build:
    name: Build docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories:
          - docker/api
          - docker/client
          - docker/dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        id: build
        run: docker build . --file ${{ matrix.directories }}/Dockerfile -t ${{ matrix.directories }}
      - name: Export Image
        id: export
        run: docker save -o ${{ matrix.directories }}${{ steps.vars.outputs.tag }}.tar ${{ matrix.directories }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.image }}
          path: ${{ matrix.directories }}${{ steps.vars.outputs.tag }}.tar
          mime-type: application/tar
