on: pull_request
name: Pull Request CI
jobs:
  install:
    name: Install dependencies
    uses: vanerac/6FIRE/.github/workflows/install_job.yml@main
  lint:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/lint_job.yml@main
  openapi:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/openapi_job.yml@main
  prisma:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/prisma_job.yml@main
  compile:
    needs: [ lint, openapi, prisma ]
    uses: vanerac/6FIRE/.github/workflows/compile_job.yml@main
  test:
    needs: [ lint, openapi, compile, prisma ]
    uses: vanerac/6FIRE/.github/workflows/test_job.yml@main
