on: push
name: Push CI
jobs:
  install:
    name: Install dependencies
    uses: vanerac/6FIRE/.github/workflows/install_job.yml@main
  lint:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/lint_job.yml@main
  openapi:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/openapi_job.yml@main
  prisma:
    needs: [ install ]
    uses: vanerac/6FIRE/.github/workflows/prisma_job.yml@main
  terraform:
    uses: vanerac/6FIRE/.github/workflows/terraform_validate_job.yml@main
  terraform_plan:
    needs: [ terraform ]
    uses: vanerac/6FIRE/.github/workflows/terraform_plan_job.yml@main
    with:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
