on:
  - release
  - workflow_dispatch
name: Release CI/CD

env:
  AWS_ACCESS_KEY_ID: ${secrets.AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${secrets.AWS_SECRET_ACCESS_KEY}
  AWS_ROLE_ARN: ${secrets.AWS_ROLE_ARN}
  SENTRY_AUTH_TOKEN: ${secrets.SENTRY_AUTH_TOKEN}
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  ECR_REPOSITORY: 6fire-${{ matrix.directories }}
  IMAGE_TAG: ${{ github.sha }}
  API_SENTRY_DSN: ${{ secrets.API_SENTRY_DSN }}
  SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
  MOLLIE_API_KEY: ${{ secrets.MOLLIE_API_KEY }}
  COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  STRIPE_PK: ${{ secrets.STRIPE_PK }}
  STRIPE_SK: ${{ secrets.STRIPE_SK }}
jobs:
  install:
    name: Install dependencies
    uses: vanerac/6FIRE/.github/workflows/install_job.yml@main
  lint:
    needs: [ install, terraform ]
    uses: vanerac/6FIRE/.github/workflows/lint_job.yml@main
  openapi:
    needs: [ install, terraform ]
    uses: vanerac/6FIRE/.github/workflows/openapi_job.yml@main
  prisma:
    needs: [ install, terraform ]
    uses: vanerac/6FIRE/.github/workflows/prisma_job.yml@main
  compile:
    needs: [ lint, openapi, prisma ]
    uses: vanerac/6FIRE/.github/workflows/compile_job.yml@main
  test:
    needs: [ lint, openapi, compile, prisma ]
    uses: vanerac/6FIRE/.github/workflows/test_job.yml@main
  terraform:
    uses: vanerac/6FIRE/.github/workflows/terraform_validate_job.yml@main
  terraform_plan:
    needs: [ terraform ]
    uses: vanerac/6FIRE/.github/workflows/terraform_plan_job.yml@main
  #  terraform_apply_ecr:
  #    needs: [ terraform_plan ]
  #    uses: vanerac/6FIRE/.github/workflows/terraform_ecr_job.yml@main
  docker_build:
    needs: [ test, compile ]
    uses: vanerac/6FIRE/.github/workflows/build_docker_job.yml@main
  terraform_deploy:
    needs: [ test, compile, docker_build ]
    uses: vanerac/6FIRE/.github/workflows/terraform_deploy_job.yml@main
