on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ROLE_ARN:
        required: true
name: Terraform Plan Job

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}

#  terraform plan -target=aws_ecr_repository.api -target=aws_ecr_repository.client -target=aws_ecr_repository.dashboard
jobs:
  ecr:
    name: Terraform Plan Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: login to AWS
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: eu-west-3
      #          role-duration-seconds: 300
      #          role-session-name: GitHubActions
      #        env:
      #          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: terraform init
        working-directory: terraform/
        name: terraform init
      - run: terraform plan #-target=aws_ecr_repository.api -target=aws_ecr_repository.client -target=aws_ecr_repository.dashboard
        working-directory: terraform/
        name: terraform plan
