on: workflow_call
name: Terraform Apply All Job

jobs:
  ecr:
    permissions:
      id-token: write
      contents: read
    name: Terraform Apply All Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: login to AWS
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: 'arn:aws:iam::339518963654:role/GithubActionsOIDC-Role-S7MH0TQ1SC7H'
          aws-region: eu-west-3
      - run: terraform init
        working-directory: terraform/
        name: terraform init
      - name: Refresh state
        working-directory: terraform/
        run: terraform apply -refresh-only
      - name: Import API ECR
        working-directory: terraform/
        run: terraform import aws_ecr_repository.api 6fire-api
        continue-on-error: true
      - name: Import Dashboard ECR
        working-directory: terraform/
        run: terraform import aws_ecr_repository.dashboard 6fire-dashboard
        continue-on-error: true
      - name: Import Client ECR
        working-directory: terraform/
        run: terraform import aws_ecr_repository.client 6fire-client
        continue-on-error: true
      - name: Import RDS
        working-directory: terraform/
        run: terraform import aws_rds_cluster.rds rds-6fire-cluster
        continue-on-error: true
      - name: Plan deployement
        working-directory: terraform/
        run: terraform plan -out=plan.file -input=false
      - name: Apply deployement
        working-directory: terraform/
        run: terraform apply -input=false plan.file
