on: workflow_call
name: Terraform Apply ECR Job

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
jobs:
  ecr:
    permissions:
      id-token: write
      contents: read
    name: Terraform Apply ECR Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositories:
          - api
          - dashboard
          - client
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: login to AWS
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: 'arn:aws:iam::339518963654:role/GithubActionsOIDC-Role-S7MH0TQ1SC7H'
          aws-region: eu-west-3
      - run: terraform init
        working-directory: terraform/
        name: terraform init
      - name: Import elements
        id: verify-state
        working-directory: terraform/
        run: terraform import aws_ecr_repository.${{matrix.repositories}} 6fire-${{matrix.repositories}}
        continue-on-error: true
      - name: Plan deployement
        if: steps.verify-state.outcome != 'success'
        env:
          valid: ${{env.valid}}
        working-directory: terraform/
        run: terraform plan -target=aws_ecr_repository.${{matrix.repositories}} -out=plan.file -input=false
      - run: terraform apply -input=false plan.file
        if: steps.verify-state.outcome != 'success'
        env:
          valid: ${{env.valid}}
        working-directory: terraform/
        name: Apply deployement
