on:
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        type: "string"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        type: "string"
        required: true
name: Terraform Plan Job

#  terraform plan -target=aws_ecr_repository.api -target=aws_ecr_repository.client -target=aws_ecr_repository.dashboard
jobs:
  ecr:
    name: Terraform Plan Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
      - run: terraform init
        working-directory: terraform/
        name: terraform init
      - run: terraform plan #-target=aws_ecr_repository.api -target=aws_ecr_repository.client -target=aws_ecr_repository.dashboard
        working-directory: terraform/
        name: terraform plan
